### ISSUE TITLE
Create a discord server

### ISSUE THREAD

**Issue by Arthurdw** [100PXSquared/pythonsourceserver#1]
Hey,

Your project seems promising, do you have a discord server?

**Comment by Derpius** [comment]
Thanks for the feedback! (first github repo btw)

I don't have a Discord set up (and i'll need to set up a non "personal" a/c), but I'll look into it now.

**Comment by Arthurdw** [comment]
Awesome, I personally use the same account for my non-personal, as discord servers can just be public and they don't have to add you as a friend or anything.

**Comment by Derpius** [comment]
Just set it up (haven't configured it yet though, and i'll add the link to the readme)

https://discord.gg/D6s5SX

**Comment by Arthurdw** [comment]
Great! ♥
